// tslint:disable
// eslint-disable
// Generated by Microsoft Kiota

export const BodyTypeObject = {
    Text: "text",
    Html: "html",
}  as const;
export type BodyType = (typeof BodyTypeObject)[keyof typeof BodyTypeObject];
// tslint:enable
// eslint-enable
