// tslint:disable
// eslint-disable
// Generated by Microsoft Kiota

export const FollowupFlagStatusObject = {
    NotFlagged: "notFlagged",
    Complete: "complete",
    Flagged: "flagged",
}  as const;
export type FollowupFlagStatus = (typeof FollowupFlagStatusObject)[keyof typeof FollowupFlagStatusObject];
// tslint:enable
// eslint-enable
