// tslint:disable
// eslint-disable
// Generated by Microsoft Kiota

export const ImportanceObject = {
    Low: "low",
    Normal: "normal",
    High: "high",
}  as const;
export type Importance = (typeof ImportanceObject)[keyof typeof ImportanceObject];
// tslint:enable
// eslint-enable
