// tslint:disable
// eslint-disable
// Generated by Microsoft Kiota

export const InferenceClassificationTypeObject = {
    Focused: "focused",
    Other: "other",
}  as const;
export type InferenceClassificationType = (typeof InferenceClassificationTypeObject)[keyof typeof InferenceClassificationTypeObject];
// tslint:enable
// eslint-enable
